### PR TITLE
double quotes are unnecessary in lua configure flags

### LINKED ISSUE #86: Lua module will be built each time
### Cookbook version

5.1.2

### Chef-client version

12.19.36

### Platform Details

Ubuntu 14.04

### Scenario:

apply with ngx_lua_module

### Steps to Reproduce:

add attribute value `chef_nginx::ngx_lua_module` to `node['nginx']['source']['modules']`

### Expected Result:

It is not compiled when it is applied twice.

### Actual Result:

Even when applied twice it will be compiled every time.

### PR DESCRIPTION
**Pull request by isaoshimizu**
### Description

If applied twice with the same version, nginx will not compile twice.

Before

https://github.com/chef-cookbooks/chef_nginx/blob/master/recipes/source.rb#L101

`node.automatic_attrs['nginx']['configure_arguments'].sort` is below (double quotes in with-ld-opt).
```
--add-module=/var/chef/cache/nginx-devel-0.3.0/ngx_devel_kit-0.3.0 --add-module=/var/chef/cache/nginx-lua-0.10.7/lua-nginx-module-0.10.7 --conf-path=/etc/nginx/nginx.conf --prefix=/opt/nginx --sbin-path=/opt/nginx/sbin/nginx --with-http_ssl_module --with-http_stub_status_module --with-http_v2_module --with-ld-opt="-Wl,-rpath,/usr/local/lib" --with-openssl=/var/chef/cache/openssl-1.0.2k
```

`nginx -V` result (no double quotes in with-ld-opt)
```
nginx version: nginx/1.11.5
built by gcc 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3)
built with OpenSSL 1.0.2k  26 Jan 2017
TLS SNI support enabled
configure arguments: --prefix=/opt/nginx --conf-path=/etc/nginx/nginx.conf --sbin-path=/opt/nginx/sbin/nginx --with-openssl=/var/chef/cache/openssl-1.0.2k --with-http_ssl_module --with-http_stub_status_module --with-http_v2_module --add-module=/var/chef/cache/nginx-lua-0.10.7/lua-nginx-module-0.10.7 --with-ld-opt=-Wl,-rpath,/usr/local/lib --add-module=/var/chef/cache/nginx-devel-0.3.0/ngx_devel_kit-0.3.0
```

### Issues Resolved

#86

### Check List

- [x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by tas50** [comment]
Ping @jimryan and @Sauraus for input on this change since you just touched all the Lua work

**Comment by Sauraus** [comment]
I will take a look at this in a few hours.

**Comment by jimryan** [comment]
If the double quotes are really unnecessary, then this looks good to me.  It's just not what's recommended in the [ngx_http_lua_module README.](https://github.com/openresty/lua-nginx-module#installation)

**Comment by tas50** [comment]
@Sauraus did you have any time to look at this?

**Comment by Sauraus** [comment]
Yes this works as well, however as @jimryan points out it doesn't follow the documented recommended method by the nginx lua module folks.

https://github.com/openresty/lua-nginx-module/issues/1022

**Comment by Sauraus** [comment]
So the `"` in the lua-nginx-module README.MD is there for no particular reason, except to show how to add multiple linker options, in which case the `"` becomes a necessity.

I've commented on the actual issue asking for clarification of what it is that's broken https://github.com/chef-cookbooks/chef_nginx/issues/86.

**Pull request merged**
