### PR TITLE
Fix only_if guard for creating the template in nginx_site

### PR DESCRIPTION
**Pull request by axos88**
### Description

Fix only_if guard for creating the template in nginx_site

Obvious fix.

### CODE REVIEW

**Comment by tas50** [comment]
Am I missing something? The default should be nil so these two should behave the same.

**Comment by axos88** [comment]
If the value is a string the contents would be evaluated as a command, and this is not what is intended

**Comment by axos88** [comment]
ping

**Comment by tas50** [comment]
not_if / only_if contents in a bracket should be evaluated as a ruby code while contents in quotes are executed as shell commands.

**Comment by axos88** [comment]
I was getting warnings, that's why I implemented the change. Will try to repro, and get back to you.

But the ruby code does not evaluate to a true / false, but a string in case the template is set. And chef will try to execute that as a command. The fact that it's in a {} block just enables to use multiple commands to generate the command to be executed.

**Comment by webframp** [comment]
Did some testing FWIW. This was the warning I saw with cookbook version 3.1.1, but I don't get it with the currently released version 4.0.1 

```
[2016-11-17T11:23:47-05:00] WARN: only_if block for template[/etc/nginx/sites-available/site001] returned "site001-nginx.erb", did
you mean to run a command? If so use 'only_if "site001-nginx.erb"' in your code.
```

**Comment by axos88** [comment]
Was getting the same warning, with 4.0.1, with chef 12.15

**Comment by axos88** [comment]
whew, that took 15 minutes to find: https://github.com/chef/chef/blob/master/lib/chef/resource/conditional.rb#L108,L109

**Comment by tas50** [comment]
That code has been refactored between the two releases. It _should_ have the correct behavior at this point. I'm going to close this one out now.

**Comment by axos88** [comment]
@tas50  @webframp branch master still has bad behaviour, as per my last email. A block returning a string is "probably a mistake", and will trigger the warning, as the linked code suggests. The block should be adjusted, as per the PR or by prepending a "!!", if you dislike changing the positiveness.

**Comment by axos88** [comment]
@tas50

**Pull request closed without merging**
