### PR TITLE
[GH-92] add passenger test suite

### LINKED ISSUE #92: Feature Request: Automated Testing for passenger
I noticed that the passenger install is not included in the Test Suite. Is there a reason for that?

Would the addition be welcomed as a pull request?

### PR DESCRIPTION
**Pull request by klyonrad**
### Description

No new functionality. The passenger functionality gets automated tests with this Pull Request.

### Issues Resolved

#92 

### Check List

- [X] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [X] New functionality includes testing.
- [X] New functionality has been documented in the README if applicable
- [X] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by klyonrad** [comment]
TODO: define necessary platforms and find a fix for at least Ubuntu 14
TODO: run passenger test suite with travis
TODO: fix Lint error

**Comment by klyonrad** [comment]
> TODO: run passenger test suite with travis
> TODO: fix Lint error

done

**Comment by klyonrad** [comment]
> TODO: define necessary platforms and find a fix for at least Ubuntu 14

Due to lack of an obvious fix available I commented out debian 7 and ubuntu 14 in the `.travis.yml`

So I consider this Pull Request finished now

EDIT: and the build failures in https://travis-ci.org/chef-cookbooks/chef_nginx/builds/219187738 look like "random" errors

**Comment by klyonrad** [comment]
Hey, what about this? Can it get merged?

**Comment by tas50** [comment]
@klyonrad There's still a few failures in Travis before this can be merged

**Comment by klyonrad** [comment]
I simply rebased onto the current `master`, before that the test build was succesful (https://travis-ci.org/chef-cookbooks/chef_nginx/builds/219187738)

since then debian 8 fails in `travis`, I can check that locally in vagrant

```
Recipe: chef_nginx::passenger

  * apt_package[ruby-dev] action install

    - install version 1:2.1.5+deb8u2 of package ruby-dev

  * apt_package[libcurl4-gnutls-dev] action install

    - install version 7.38.0-4+deb8u5 of package libcurl4-gnutls-dev

  * gem_package[rake] action install

    

    ================================================================================

    Error executing action `install` on resource 'gem_package[rake]'

    ================================================================================

    

    Chef::Exceptions::FileNotFound

    ------------------------------

    Unable to find 'gem' binary in path: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

    

    Resource Declaration:

    ---------------------

    # In /opt/kitchen/cache/cookbooks/chef_nginx/recipes/passenger.rb

    

     32: gem_package 'rake' if node['nginx']['passenger']['install_rake']

     33: 

    

    Compiled Resource:

    ------------------

    # Declared in /opt/kitchen/cache/cookbooks/chef_nginx/recipes/passenger.rb:32:in `from_file'

    

    gem_package("rake") do

      package_name "rake"

      action [:install]

      default_guard_interpreter :default

      declared_type :gem_package

      cookbook_name "chef_nginx"

      recipe_name "passenger"

    end

    

    System Info:

    ------------

    chef_version=13.1.6

    platform=debian

    platform_version=8.8

    ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]

    program_name=chef-client worker: ppid=71;start=14:23:21;

    executable=/opt/chef/embedded/bin/chef-client
```

**Comment by klyonrad** [comment]
The test suite is running through now on Travis.

Can you merge this?

Greetings

**Comment by tas50** [comment]
Thanks for putting this all together. This will help us keep the passenger side of things stable

**Pull request merged**
